all:
  hosts:
    linux:
      ubn:
        ansible_host: 172.16.0.21
        ansible_connection: ssh
      netbox:
        ansible_host: 172.16.0.159
        ansible_connection: ssh
    windows:
      isbashgu-app02:
        ansible_host: 62.76.8.55
        ansible_connection: winrm
        ansible_winrm_transport: basic
      server4.example.com:
        ansible_host: server4.example.com
        ansible_connection: winrm
        ansible_winrm_transport: basic

